name: Build and Push to ACR

on:
  push:
    branches:
      - main

env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  TAG: ${{ secrets.REGISTRY_LOGIN_SERVER }}/pdfchat_backend:kube4


jobs:
  continuous-integration:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: set_path
      run: |
        export CLOUDSDK_PYTHON=/usr/bin/python
        
    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Build the backend pdfchat
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: "${{ env.TAG }}"
        file: Dockerfile
    